# Generated by Django 2.1.3 on 2018-11-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DormsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('住址编号', models.CharField(max_length=15, unique=True)),
                ('住址', models.TextField()),
                ('剩余电量', models.FloatField()),
                ('上次充值时间', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('联系人', models.CharField(max_length=15)),
                ('联系方式', models.CharField(max_length=100)),
                ('问题', models.TextField()),
                ('提交时间', models.DateTimeField(auto_now_add=True)),
                ('是否解决', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('卡上余额', models.FloatField()),
                ('水费余额', models.FloatField()),
                ('上次充值时间', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('学号', models.CharField(max_length=15, unique=True)),
                ('姓名', models.CharField(max_length=15)),
                ('性别', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2)),
                ('住址编号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.DormsInfo')),
            ],
        ),
        migrations.AddField(
            model_name='studentsbalance',
            name='学号',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='weixin.StudentsInfo'),
        ),
    ]
